### PR TITLE
Updated version of E@H build for new PyCBC

### PR DESCRIPTION
**Pull request by duncan-brown**
This is a pull request to keep track of my changes to the bundling script. So far I have:

- Added a build target for SL6 to match my build VM.
- Configured the SL6 build to build and install Python 2.7 as SL6 has Python 2.6.
- Use the python source from Pegasus 4.7 which also removes the need for ``psycopg``.
- Add a variable to allow us to use gcc from ``/usr/bin``  on SL6.
- Download a tarball containing the ROM data and use that in the test.
- Add the command line ``--sample-rate 2048`` to trigger downsampling
- Change the approximant to ``--approximant 'SPAtmplt:mtotal<4' 'SEOBNRv2_ROM_DoubleSpin:else'``

### CODE REVIEW

**Comment by duncan-brown** [comment]
@bema-ligo I'm still testing this, so please hold off merging for the moment.

**Comment by duncan-brown** [comment]
To get a full build you also need `--cluster-function symmetric` which builds the matched filter and symmetric clustering function, as well as at least one SPAtmplt in the bank.

**Comment by duncan-brown** [comment]
@bema-ligo this is ready to merge. I tested it with the new command line and it works

```
LAL_DATA_PATH=/cvmfs/oasis.opensciencegrid.org/ligo/pipeline/pycbc/pycbc/ROM/lal-data/lalsimulation \
NO_TMPDIR=1 \
./pycbc_inspiral_osg_duncan \
  --pad-data   8   --strain-high-pass   20   --sample-rate   2048 \
  --segment-length   512   --segment-start-pad   112   --segment-end-pad   16 \
  --allow-zero-padding   --taper-data   1   --psd-estimation   median \
  --psd-segment-length   16   --psd-segment-stride   8   --psd-inverse-length 16 \
  --psd-num-segments   63   --autogating-threshold   100 \
  --autogating-cluster   0.5   --autogating-width   0.25   --autogating-taper 0.25 \
  --autogating-pad   16   --low-frequency-cutoff   30  \
  --approximant 'SPAtmplt:mtotal<4' 'SEOBNRv2_ROM_DoubleSpin:else' \
  --snr-threshold   5.5   --cluster-method   window   --cluster-window   1 \
  --cluster-function   symmetric   \
  --chisq-bins "1.75*(get_freq('fSEOBNRv2Peak',params.mass1,params.mass2,params.spin1z,params.spin2z)-60.)**0.5" \
  --newsnr-threshold   5   --filter-inj-only   --injection-window   4.5 \
  --channel-name H1:DCS-CALIB_STRAIN_C02 \
  --gps-start-time   1134457430   --gps-end-time 1134459478   \
  --trig-start-time   1134457547   --trig-end-time   1134459427 \
  --injection-file   H1L1-STRIP_INJECTIONS_BBH01_INJ-1134450017-1202400.xml \
  --output   H1-INSPIRAL_BBH01_INJ_JOB0-1134457547-1880-${1}-${2}.hdf \
  --frame-files   H-H1_HOFT_C02-1134456832-4096.gwf    \
  --bank-file H1L1-PREGEN_TMPLTBANK_SPLITBANK_BANK0-1134450017-1202400.xml.gz \
  --user-tag BBH01_INJ_JOB0 \
  --verbose --fixed-weave-cache
```

**Comment by bema-aei** [comment]
Thanks. The Pegasus update might work on SL6 and might even be required for OSG, but I strongly doubt that this will work on E@H platforms like Cygwin. I'll test this and come up with a solution that will be  configurable for SL6 / OSG.

**Comment by bema-aei** [comment]
Works, though. Will merge, then fix downloads.

**Pull request merged**
