### PR TITLE
add a command line argument to drop extra so files into the bundle

### PR DESCRIPTION
**Pull request by duncan-brown**
Add a command line argument to allow the user to specify a path from which to pull extra ``.so`` files and drop them in the bundle. This allows the user to e.g. add MKL libraries with:

```
./pycbc_build_eah.sh --with-extra-libs=/opt/intel/mkl/lib/intel64
```

```
>> [Mon Nov  7 14:03:54 EST 2016] zipping weave cache


>> [Mon Nov  7 14:03:54 EST 2016] adding extra libraries from /opt/intel/mkl/lib/intel64
  adding: pycbc_inspiral/ (stored 0%)
  adding: pycbc_inspiral/libmkl_avx2.so (deflated 68%)
  adding: pycbc_inspiral/libmkl_def.so (deflated 65%)
  adding: pycbc_inspiral/linux227compiled_catalog (deflated 94%)
  adding: pycbc_inspiral/libmkl_core.so (deflated 65%)
  adding: pycbc_inspiral/libmkl_tbb_thread.so (deflated 65%)
  adding: pycbc_inspiral/sc_10963aa999b5155610acf1203d1e1f2f0.cpp (deflated 83%)
  adding: pycbc_inspiral/sc_f39a3063d4a40a475138d02a006ac88a0.so (deflated 62%)
  adding: pycbc_inspiral/sc_0824510149a0cf3967b746b0273477930.cpp (deflated 83%)
  adding: pycbc_inspiral/libmkl_sequential.so (deflated 64%)
  adding: pycbc_inspiral/sc_10963aa999b5155610acf1203d1e1f2f0.so (deflated 62%)
  adding: pycbc_inspiral/libmkl_mc.so (deflated 65%)
  adding: pycbc_inspiral/libmkl_vml_def.so (deflated 56%)
  adding: pycbc_inspiral/sc_8ac50855f43f26429ce465e79758bdf20.cpp (deflated 83%)
  adding: pycbc_inspiral/sc_fded9885ef54da8de785c3ccab719a980.so (deflated 62%)
  adding: pycbc_inspiral/sc_0824510149a0cf3967b746b0273477930.so (deflated 62%)
  adding: pycbc_inspiral/libmkl_vml_avx512_mic.so (deflated 58%)
  adding: pycbc_inspiral/sc_69aefe017927593ea71555386ce023aa0.cpp (deflated 82%)
  adding: pycbc_inspiral/libmkl_intel_lp64.so (deflated 73%)
  adding: pycbc_inspiral/sc_2107325a10e2db4369323937223875580.so (deflated 62%)
  adding: pycbc_inspiral/libmkl_vml_avx2.so (deflated 60%)
  adding: pycbc_inspiral/libmkl_mc3.so (deflated 64%)
  adding: pycbc_inspiral/libmkl_vml_avx.so (deflated 60%)
  adding: pycbc_inspiral/sc_69aefe017927593ea71555386ce023aa0.so (deflated 62%)
  adding: pycbc_inspiral/libmkl_vml_cmpt.so (deflated 59%)
  adding: pycbc_inspiral/sc_fded9885ef54da8de785c3ccab719a980.cpp (deflated 83%)
  adding: pycbc_inspiral/sc_2107325a10e2db4369323937223875580.cpp (deflated 83%)
  adding: pycbc_inspiral/libmkl_gnu_thread.so (deflated 69%)
  adding: pycbc_inspiral/libmkl_vml_avx512.so (deflated 59%)
  adding: pycbc_inspiral/sc_8ac50855f43f26429ce465e79758bdf20.so (deflated 66%)
  adding: pycbc_inspiral/libmkl_avx512.so (deflated 69%)
  adding: pycbc_inspiral/libmkl_intel_thread.so (deflated 68%)
  adding: pycbc_inspiral/libmkl_vml_mc.so (deflated 59%)
  adding: pycbc_inspiral/libmkl_gf_ilp64.so (deflated 76%)
  adding: pycbc_inspiral/libmkl_vml_mc2.so (deflated 59%)
  adding: pycbc_inspiral/libmkl_avx.so (deflated 61%)
  adding: pycbc_inspiral/libmkl_intel_ilp64.so (deflated 76%)
  adding: pycbc_inspiral/sc_f39a3063d4a40a475138d02a006ac88a0.cpp (deflated 83%)
  adding: pycbc_inspiral/libmkl_vml_mc3.so (deflated 59%)
  adding: pycbc_inspiral/libmkl_rt.so (deflated 77%)
  adding: pycbc_inspiral/sc_40483404101af0543784db5ff1f1cfe40.so (deflated 63%)
  adding: pycbc_inspiral/libmkl_avx512_mic.so (deflated 70%)
  adding: pycbc_inspiral/sc_40483404101af0543784db5ff1f1cfe40.cpp (deflated 79%)
  adding: pycbc_inspiral/libmkl_gf_lp64.so (deflated 73%)
  adding: SEOBNRv2ChirpTimeSS.dat (deflated 3%)
```

### CODE REVIEW

**Comment by bema-aei** [comment]
This limits usage to files that are located somewhere on the build machine. It would be more flexible to e.g. specify a URL with a zip file or tarball that can contain any additional files to be added (possibly including, but not limited to, local directories)

**Comment by bema-aei** [comment]
Or would it make sense to maintain such files in the PyCBC repo, e.g. in tools/einsteinathome/extra-libs/ ?

**Comment by duncan-brown** [comment]
@bema-ligo I don't think we can maintain the Intel MKL libs in the repo, as the license says that they can be redistributed with the "application." Posting the `.so` files online might violate the license as that's not in the application.

https://software.intel.com/en-us/articles/intel-math-kernel-library-licensing-faq#redistribute

But I think we could post them on an internal site for the build process. Do you want me to modify this to pull from a URL location?

**Comment by bema-aei** [comment]
@duncan-brown:

>  Do you want me to modify this to pull from a URL location?

Yes, I think that would be more flexible and thus better.

**Pull request closed without merging**
